# secrets.toml en Streamlit Cloud
[google_drive]
type = "service_account"
project_id = "analisclientes"
private_key_id = "a6075ca950a9b2bd3fe6287b6558b4469d28f1f5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDGLTwDHMfMfFvX
4SuLCPbIiJw6ALoxWVlz80V48XcoWvxbOYhHiJ0BoAnbYtfZ+Z37FTBgNl2sgBjz
JOjG/7QYWSru5lVEA5k7QbeOARZBHnXKPO+cxScabJ/n3s6kkO1kOjkyVW1f466U
IGSIfZRFYof6E+K06RQeZmICefdyu+nO9WNF2CSKLXtJlPvvlp+VqTXa6IQ1B+Hy
eBUsP8unBAFabUJSKsEkJS6lskgQtGn9uRXz2k7Yhz0PL+JKTYsTCRYiZRfkoiGq
blB9C8Y1tpBliSMYpPq1oEv6Vzu0al3tgwi7LzAXwesGtv60B+4rdqcxunoYCCQJ
erTWjrzfAgMBAAECggEABWZqi52Q82LltpTQwYgfMvwUYOw8jQDlrbT3Gdv483H1
ptK2T1fkpCYYcd1YPmNNfIlpeQwVZcO6Nx3nwRk31Uk3IOCVec+TSrvesZFMA76k
I2+hPXQncNJKHscoE4nmpH2Fqd50DYUM8JJbyvBV38VW9gFTgyFHk0OwIs5Wzme0
j9P62S6pfUnT8KW2NrC/BkUHgROijIwB/UCwQ2nrYC9taZLDL9ca/FSoJ3xhV7SP
S1RR9lPVb+LGGqFnizAwSdJl1QgfeM/p9rVH3YTuDRiWbCQso2juGdqgbuBJ53kn
EFzYUI3VuEhCrtpqaV6IOJjEjGKYTDedSzYI9BxbSQKBgQDhvUmgz/HWLu0dS5+5
KR8j3MCQ7GVwwMqP3j4bRISz89L1NBWEb6/M21ABAiBPfGGg//eZsHc7NxJcRt2T
rNHjACoHeDpALMlNwobwVtpZH4vXHcToqsA1O66Hfb7k9s9Jn06UMGU5Pi52RPK8
pJRPcZz0DSJeJiBx4orxtMBBQwKBgQDgvhNkmS1mIan8VD/LtLJbNSGAeeN92nTd
YYLlytyq2ezXIz/6wIVi+gLWob6iwYW0RzyOJZlMREaE5H07EBbW8tzQL+wYsfFf
jqypdcE2qoDN/Z/vJHkC5B9BXHdtgrVLFBpEk4praGp2SfAdZI3a4xvoeiB0a7Xh
Dbd1TJE+NQKBgQDEqixjNcbzWp6pTyEwJ2tByyjZGZqmyM+w12Y0S1VxkZLQnTfB
0avPRaJFvpx3o11K7rW/58V4iVotmm+gIIgaxCHZsBzPnDUk0bzN1l0UGC+0kfLi
4R/jQMOktyCASaX99hR3dlI5tLq1vwva3Wd4bvrWhDrU21KY5U03lsmIEQKBgBfR
zXhiC7/BXaTSwRg0BJtKHEzjnkrednhoN1lnkM/C3SlIISXQddKxsM9SwUO6wxMC
YdanAYJl0huPo/44jFMn1mNyUNGlOnHoS0CCrIHAvHoYoXTVJsY5q15gEIBY1CIq
9UXDZW5Q2MfEumBDIg3K+FBBcWMlb1d0/ra98L7pAoGBAMHKkIMg3vT1ePGN620O
Lz2edM5di13X+uZ0Fl3VgHqu3IVt6kKE6cKw72kpNHcGYKLUpugw0C3lC9655YKF
YnMIbiHxIAI/5nNXBdlnw8vuON36aBmNeMQp2R5XfHneon6W/44ttKZAWKZ7X2n5
H1HtVmRrQl1mG9ulhvNaKJbr
-----END PRIVATE KEY-----"""
client_email = "mkoncept@analisclientes.iam.gserviceaccount.com"
client_id = "102659346598615181210"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mkoncept%40analisclientes.iam.gserviceaccount.com"
folder_id = "1kcuV4rPOArBZoZea5PFFsqkMU5A_dHQs"
# HOME DEPOT DATA BASE
file_id = "1iqMYfMWs-S-fF-LLy5X7ZxeBsVtxNgB7"
# El file ID del archivo 'DATAHD.xlsx'
datahd_file_id = "1BmdUCqnsaX8-7o_-z6tBgGQB199rn1Ej"  # Coloca aquí el file ID de tu archivo DATAHD.xlsx
# INTER DATA BASE
file_id_inter ="1qjJNeyCFa4SOEESyeTXXe7zYXcV91fdkvLTFKdPLROw"
# SKUS
file_id_kohler = "1B81I9bsY63TB1PaR8_SaKVpETIJOQ3oK"
file_id_skus = "1F7vPs2DgaFU481spfX7XGvGcHkk6he7r"